// <auto-generated />
using System;
using DbLogger.Tests.DbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DbLogger.Migrations
{
    [DbContext(typeof(LogSuccessDbContext))]
    [Migration("20230202174616_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.12");

            modelBuilder.Entity("DbLogger.LogEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ChangedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("Context")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ContextId")
                        .HasColumnType("TEXT");

                    b.Property<string>("CurrentValue")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("LogType")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("LogTypeBy")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("PreviousValue")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Property")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<uint>("Revision")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Logs");
                });

            modelBuilder.Entity("DbLogger.Tests.Misc.Entity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Entities");
                });
#pragma warning restore 612, 618
        }
    }
}
